"""Added tables

Revision ID: c81aac73e4f1
Revises: dc403c8b2c39
Create Date: 2024-01-09 01:22:14.541642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c81aac73e4f1'
down_revision = 'dc403c8b2c39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
